### ISSUE TITLE
Expected Number of Concurrent Users

### ISSUE THREAD

**Issue by cotopaxisummit** [18F/bpa-disaster-data-portal-pilot#7]
# Question/Comment on the HUD Disaster Data Portal Pilot Program

## Name and affiliation
Todd Hutchison – PwC Contracts Manager

## Section of RFQ documents
PWS, Page 4, Section 5.0 Tasks

## Question/Comment
Can the government provide an estimate on the expected number of concurrent users of the system?

**Comment by randyhart** [comment]
Were the system to go live today, the total number of users would be based on the number of active CDBG-DR grants, which can be viewed here: https://www.hudexchange.info/programs/cdbg-dr/cdbg-dr-grantee-contact-information/#all-disasters That would be a maximum load numbering in the hundreds. But the successful system will be sufficiently modular and flexible to allow it to be scaled within a cloud-hosting environment, to accommodate a wide range of concurrent users, because there is no upper bound on the impact of large-scale natural disasters.
